// <auto-generated />
using System;
using HealthcareMini.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthcareMini.Migrations
{
    [DbContext(typeof(HealthcareDbContext))]
    partial class HealthcareDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoctorHealthCareCenter", b =>
                {
                    b.Property<int>("DoctorsId")
                        .HasColumnType("int");

                    b.Property<int>("HealthCareCentersId")
                        .HasColumnType("int");

                    b.HasKey("DoctorsId", "HealthCareCentersId");

                    b.HasIndex("HealthCareCentersId");

                    b.ToTable("DoctorHealthCareCenter");
                });

            modelBuilder.Entity("HealthCareCenterReceptionist", b =>
                {
                    b.Property<int>("HealthCareCentersId")
                        .HasColumnType("int");

                    b.Property<int>("ReceptionistsId")
                        .HasColumnType("int");

                    b.HasKey("HealthCareCentersId", "ReceptionistsId");

                    b.HasIndex("ReceptionistsId");

                    b.ToTable("HealthCareCenterReceptionist");
                });

            modelBuilder.Entity("HealthCareCenterStaff", b =>
                {
                    b.Property<int>("HealthCareCentersId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("HealthCareCentersId", "StaffId");

                    b.HasIndex("StaffId");

                    b.ToTable("HealthCareCenterStaff");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AppointmentEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("HealthCareCenterId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ReasonForVisit")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("HealthCareCenterId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.HealthCareCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HealthCareCenters");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("HealthCareCenterId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("HealthCareCenterId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfRegistration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.Admin", b =>
                {
                    b.HasBaseType("HealthcareMini.Models.Entitys.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.Doctor", b =>
                {
                    b.HasBaseType("HealthcareMini.Models.Entitys.User");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("Users", t =>
                        {
                            t.Property("Salary")
                                .HasColumnName("Doctor_Salary");
                        });

                    b.HasDiscriminator().HasValue("Doctor");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.Patient", b =>
                {
                    b.HasBaseType("HealthcareMini.Models.Entitys.User");

                    b.HasDiscriminator().HasValue("Patient");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.Receptionist", b =>
                {
                    b.HasBaseType("HealthcareMini.Models.Entitys.User");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.ToTable("Users", t =>
                        {
                            t.Property("Salary")
                                .HasColumnName("Receptionist_Salary");
                        });

                    b.HasDiscriminator().HasValue("Receptionist");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.Staff", b =>
                {
                    b.HasBaseType("HealthcareMini.Models.Entitys.User");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Staff");
                });

            modelBuilder.Entity("DoctorHealthCareCenter", b =>
                {
                    b.HasOne("HealthcareMini.Models.Entitys.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthcareMini.Models.Entitys.HealthCareCenter", null)
                        .WithMany()
                        .HasForeignKey("HealthCareCentersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthCareCenterReceptionist", b =>
                {
                    b.HasOne("HealthcareMini.Models.Entitys.HealthCareCenter", null)
                        .WithMany()
                        .HasForeignKey("HealthCareCentersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthcareMini.Models.Entitys.Receptionist", null)
                        .WithMany()
                        .HasForeignKey("ReceptionistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthCareCenterStaff", b =>
                {
                    b.HasOne("HealthcareMini.Models.Entitys.HealthCareCenter", null)
                        .WithMany()
                        .HasForeignKey("HealthCareCentersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthcareMini.Models.Entitys.Staff", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.Appointment", b =>
                {
                    b.HasOne("HealthcareMini.Models.Entitys.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthcareMini.Models.Entitys.HealthCareCenter", "HealthCareCenter")
                        .WithMany("Appointments")
                        .HasForeignKey("HealthCareCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthcareMini.Models.Entitys.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("HealthCareCenter");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.HealthCareCenter", b =>
                {
                    b.OwnsOne("HealthcareMini.Models.Objects.AddressDetails", "AddressDetails", b1 =>
                        {
                            b1.Property<int>("HealthCareCenterId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<int?>("Province")
                                .HasColumnType("int");

                            b1.Property<string>("Street")
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)");

                            b1.Property<string>("ZipCode")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.HasKey("HealthCareCenterId");

                            b1.ToTable("HealthCareCenters");

                            b1.WithOwner()
                                .HasForeignKey("HealthCareCenterId");
                        });

                    b.OwnsOne("HealthcareMini.Models.Objects.ContactDetails", "ContactDetails", b1 =>
                        {
                            b1.Property<int>("HealthCareCenterId")
                                .HasColumnType("int");

                            b1.PrimitiveCollection<string>("PhoneNumbers")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("HealthCareCenterId");

                            b1.ToTable("HealthCareCenters");

                            b1.WithOwner()
                                .HasForeignKey("HealthCareCenterId");
                        });

                    b.Navigation("AddressDetails")
                        .IsRequired();

                    b.Navigation("ContactDetails")
                        .IsRequired();
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.MedicalRecord", b =>
                {
                    b.HasOne("HealthcareMini.Models.Entitys.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthcareMini.Models.Entitys.HealthCareCenter", "HealthCareCenter")
                        .WithMany()
                        .HasForeignKey("HealthCareCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthcareMini.Models.Entitys.Patient", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("HealthCareCenter");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.User", b =>
                {
                    b.OwnsOne("HealthcareMini.Models.Objects.AddressDetails", "AddressDetails", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<string>("Province")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("AddressDetails_Province");

                            b1.Property<string>("Street")
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)");

                            b1.Property<string>("ZipCode")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("HealthcareMini.Models.Objects.ContactDetails", "ContactDetails", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.PrimitiveCollection<string>("PhoneNumbers")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ContactDetails_PhoneNumbers");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("AddressDetails")
                        .IsRequired();

                    b.Navigation("ContactDetails")
                        .IsRequired();
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.HealthCareCenter", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.Patient", b =>
                {
                    b.Navigation("MedicalRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
