// <auto-generated />
using HealthcareMini.Data;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;

#nullable disable

namespace HealthcareMini.Migrations
{
    [DbContext(typeof(HealthcareDbContext))]
    [Migration("20260520093207_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoctorHealthCareCenter", b =>
                {
                    b.Property<int>("DoctorsId")
                        .HasColumnType("int");

                    b.Property<int>("HealthCareCenterId")
                        .HasColumnType("int");

                    b.HasKey("DoctorsId", "HealthCareCenterId");

                    b.HasIndex("HealthCareCenterId");

                    b.ToTable("HealthCareCenterDoctors", (string)null);
                });

            modelBuilder.Entity("HealthCareCenterReceptionist", b =>
                {
                    b.Property<int>("HealthCareCenterId")
                        .HasColumnType("int");

                    b.Property<int>("ReceptionistsId")
                        .HasColumnType("int");

                    b.HasKey("HealthCareCenterId", "ReceptionistsId");

                    b.HasIndex("ReceptionistsId");

                    b.ToTable("HealthCareCenterReceptionists", (string)null);
                });

            modelBuilder.Entity("HealthCareCenterStaff", b =>
                {
                    b.Property<int>("HealthCareCenterId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("HealthCareCenterId", "StaffId");

                    b.HasIndex("StaffId");

                    b.ToTable("HealthCareCenterStaff", (string)null);
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AppointmentEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("HealthCareCenterId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ReasonForVisit")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentDate");

                    b.HasIndex("HealthCareCenterId");

                    b.HasIndex("PatientId");

                    b.HasIndex("DoctorId", "AppointmentDate");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.HealthCareCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasMaxLength(400)
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("HealthCareCenters");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("HealthCareCenterId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("HealthCareCenterId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressDetailsId")
                        .HasColumnType("int");

                    b.Property<int>("ContactDetailsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfRegistration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("AddressDetailsId");

                    b.HasIndex("ContactDetailsId");

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HealthcareMini.Models.Objects.AddressDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("AddressDetails");
                });

            modelBuilder.Entity("HealthcareMini.Models.Objects.ContentDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("ContentDetails");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.Admin", b =>
                {
                    b.HasBaseType("HealthcareMini.Models.Entitys.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.Doctor", b =>
                {
                    b.HasBaseType("HealthcareMini.Models.Entitys.User");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("Specialization");

                    b.ToTable("Users", t =>
                        {
                            t.Property("Salary")
                                .HasColumnName("Doctor_Salary");
                        });

                    b.HasDiscriminator().HasValue("Doctor");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.Patient", b =>
                {
                    b.HasBaseType("HealthcareMini.Models.Entitys.User");

                    b.HasDiscriminator().HasValue("Patient");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.Receptionist", b =>
                {
                    b.HasBaseType("HealthcareMini.Models.Entitys.User");

                    b.Property<double>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.ToTable("Users", t =>
                        {
                            t.Property("Salary")
                                .HasColumnName("Receptionist_Salary");
                        });

                    b.HasDiscriminator().HasValue("Receptionist");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.Staff", b =>
                {
                    b.HasBaseType("HealthcareMini.Models.Entitys.User");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.HasDiscriminator().HasValue("Staff");
                });

            modelBuilder.Entity("DoctorHealthCareCenter", b =>
                {
                    b.HasOne("HealthcareMini.Models.Entitys.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthcareMini.Models.Entitys.HealthCareCenter", null)
                        .WithMany()
                        .HasForeignKey("HealthCareCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthCareCenterReceptionist", b =>
                {
                    b.HasOne("HealthcareMini.Models.Entitys.HealthCareCenter", null)
                        .WithMany()
                        .HasForeignKey("HealthCareCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthcareMini.Models.Entitys.Receptionist", null)
                        .WithMany()
                        .HasForeignKey("ReceptionistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthCareCenterStaff", b =>
                {
                    b.HasOne("HealthcareMini.Models.Entitys.HealthCareCenter", null)
                        .WithMany()
                        .HasForeignKey("HealthCareCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthcareMini.Models.Entitys.Staff", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.Appointment", b =>
                {
                    b.HasOne("HealthcareMini.Models.Entitys.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthcareMini.Models.Entitys.HealthCareCenter", "HealthCareCenter")
                        .WithMany("Appointments")
                        .HasForeignKey("HealthCareCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthcareMini.Models.Entitys.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("HealthCareCenter");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.MedicalRecord", b =>
                {
                    b.HasOne("HealthcareMini.Models.Entitys.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthcareMini.Models.Entitys.HealthCareCenter", "HealthCareCenter")
                        .WithMany()
                        .HasForeignKey("HealthCareCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthcareMini.Models.Entitys.Patient", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("HealthCareCenter");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.User", b =>
                {
                    b.HasOne("HealthcareMini.Models.Objects.AddressDetails", "AddressDetails")
                        .WithMany()
                        .HasForeignKey("AddressDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthcareMini.Models.Objects.ContentDetails", "ContactDetails")
                        .WithMany()
                        .HasForeignKey("ContactDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddressDetails");

                    b.Navigation("ContactDetails");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.HealthCareCenter", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("HealthcareMini.Models.Entitys.Patient", b =>
                {
                    b.Navigation("MedicalRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
